### ISSUE TITLE
[Question] How do you use function fragments

### ISSUE THREAD

**Issue by Igrium** [PavelKastornyy/ansi4j#7]
I've been working on a terminal emulator using this library, and I'm a little confused as to how to actually use a `FunctionFragment` once you've obtained it. Text fragments seem simple enough, but a function fragment doesn't appear to offer any methods that help you understand what it is. Am I not doing this right?

```java
while ((fragment = parser.parse()) != null) {
    if (fragment.getType() == FragmentType.FUNCTION) {
        FunctionFragment funcFragment = (FunctionFragment) fragment;
        // How to get function details?
    } else {
        writeText(fragment.getText());
    }
}
```

**Comment by pcastornii** [comment]
Hello @Sam54123. Having `FunctionFragment` you can use methods defined in [FunctionFragment](https://github.com/PavelKastornyy/ansi4j/blob/master/ansi4j-core-api/src/main/java/pk/ansi4j/core/api/FunctionFragment.java) and [Fragment](https://github.com/PavelKastornyy/ansi4j/blob/master/ansi4j-core-api/src/main/java/pk/ansi4j/core/api/Fragment.java) interfaces.

Mainly you use two methods - `getFunction()` to the function that is parsed (all functions are enumerations, for details see this [package](https://github.com/PavelKastornyy/ansi4j/tree/master/ansi4j-core-api/src/main/java/pk/ansi4j/core/api/iso6429)) and `getArguments()` to get function arguments. 

So, you have everything what you need - function and its arguments. What you will do with them it is up to you and your application.
